// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(document).ready(function($) {
    var $checkboxes, $subscriptions_div, checked, e, saveOptions, _i, _len, _results;
    $subscriptions_div = $('#ml_admin_subscriptions');
    $checkboxes = $("#ml_admin_subscriptions_options input[type='checkbox']");
    saveOptions = function() {
      var checked, data, e, name, _i, _len;
      data = {
        action: 'ml_admin_subscriptions_save_options'
      };
      for (_i = 0, _len = $checkboxes.length; _i < _len; _i++) {
        e = $checkboxes[_i];
        name = $(e).attr('name');
        checked = $(e).is(':checked');
        data[name] = checked;
      }
      console.log(data);
      return $.ajax({
        url: ajaxurl,
        data: data,
        type: 'POST',
        dataType: 'html',
        success: function(response) {}
      });
    };
    $("#ml_admin_subscriptions_options input[type='submit']").click(function() {
      return saveOptions();
    });
    _results = [];
    for (_i = 0, _len = $checkboxes.length; _i < _len; _i++) {
      e = $checkboxes[_i];
      checked = $(e).data('checked');
      if (checked) {
        _results.push($(e).attr('checked', true));
      } else {
        $(e).attr('checked', false);
        _results.push($(e).removeAttr('checked'));
      }
    }
    return _results;
  });

}).call(this);
