// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(document).ready(function($) {
    var $admob_div, $html_div, $page, $select;
    $admob_div = $('#ml_admin_banners_admob');
    $html_div = $('#ml_admin_banners_html');
    $page = $('#ml_admin_banners');
    $select = $page.find('select#ml_admin_banners_service_select');
    $select.change(function() {
      var v;
      v = $(this).val();
      $admob_div.hide();
      $html_div.hide();
      if (v === 'admob') {
        return $admob_div.show();
      } else if (v === 'html') {
        return $html_div.show();
      }
    });
    $select.val($select.data('selected')).trigger('change');
    return $('#ml_admin_banners_save_btn').click(function() {
      var data, saving_label,
        _this = this;
      saving_label = $(this).data('saving-label');
      $(this).val(saving_label).attr('disabled', true);
      data = {
        action: 'ml_admin_banners_save',
        banners_service: $select.val(),
        ml_banners_admob_phone_id: $('#admob_phone_id').val(),
        ml_banners_admob_tablet_id: $('#admob_tablet_id').val(),
        ml_banners_html_phone_top: $('#html_phone_top').val(),
        ml_banners_html_phone_article_top: $('#html_phone_article_top').val(),
        ml_banners_html_phone_article_bottom: $('#html_phone_article_bottom').val(),
        ml_banners_html_tablet_top: $('#html_tablet_top').val(),
        ml_banners_html_tablet_article_top: $('#html_tablet_article_top').val(),
        ml_banners_html_tablet_article_bottom: $('#html_tablet_article_bottom').val()
      };
      return $.post(ajaxurl, data, function(response) {
        var label;
        label = $(_this).data('label');
        $(_this).attr('disabled', false);
        return $(_this).val(label);
      });
    });
  });

}).call(this);
