// Generated by CoffeeScript 1.6.3
(function() {
  var makeFluidMedia, makePageSpinner, updateMedia;

  $(document).ready(function() {
    return mobiloud_mobile_init();
  });

  window.mobiloud_mobile_init = function() {
    var $filtered_content, loadImages;
    $('#loading_spinner').remove();
    $('img, embed, object, video, iframe').wrap("<div class='media-container'></div>");
    loadImages = function() {
      var img, _i, _len, _ref, _results;
      _ref = $('img');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        img = _ref[_i];
        $(img).removeAttr('width').removeAttr('height').removeAttr('class');
        $(img).closest("[id^=attachment]").removeAttr('style').removeAttr('class');
        _results.push($(img).show());
      }
      return _results;
    };
    loadImages();
    makeFluidMedia();
    $filtered_content = $('.post-content').contents().filter(function() {
      return this.nodeType === 3;
    });
    $filtered_content.wrap("<div class='post-text'></div>");
    return makePageSpinner();
  };

  updateMedia = function() {
    var $fluidEl, $medias, newWidth;
    $fluidEl = $('.post-content');
    newWidth = $fluidEl.width() - 30;
    $medias = $('embed, object, video, iframe');
    return $medias.each(function() {
      var $el;
      $el = $(this);
      $el.attr('width', newWidth);
      return $el.attr('height', newWidth * $el.data('aspect-ratio'));
    });
  };

  makeFluidMedia = function() {
    var $fluidEl, $medias;
    $fluidEl = $('.post-content');
    $medias = $('embed, object, video, iframe');
    $medias.each(function() {
      $(this).data('aspect-ratio', this.height / this.width);
      $(this).removeAttr('width');
      return $(this).removeAttr('height');
    });
    $(window).resize(function() {
      return updateMedia();
    });
    $(window).resize();
    return updateMedia();
  };

  makePageSpinner = function() {
    var opts, spinner, target;
    opts = {
      lines: 13,
      length: 20,
      width: 10,
      radius: 30,
      corners: 1,
      rotate: 0,
      direction: 1,
      color: '#000',
      speed: 1,
      trail: 60,
      shadow: false,
      hwaccel: false,
      className: 'spinner',
      zIndex: 2e9,
      top: 'auto',
      left: 'auto'
    };
    target = document.getElementById('loading_spinner');
    return spinner = new Spinner(opts).spin(target);
  };

}).call(this);
