// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var $lazy_info, post_id, url;
    $lazy_info = $('#mobiloud_lazy_load');
    url = $lazy_info.data('url');
    post_id = $lazy_info.data('post_id');
    return $.ajax({
      type: 'GET',
      url: url,
      contentType: 'application/json',
      dataType: 'jsonp',
      data: {
        post_id: post_id
      },
      error: function(data, status, error) {
        return console.log(error);
      },
      success: function(data) {
        var $body_content;
        $body_content = $(data.body_content);
        $('#lazy_body').hide().html($body_content).show();
        return mobiloud_mobile_init();
      }
    });
  });

}).call(this);
